/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'case-studies': CaseStudy;
    insights: Insight;
    announcements: Announcement;
    team: Team;
    reports: Report;
    'use-cases': UseCase;
    bookings: Booking;
    'trust-logos': TrustLogo;
    clients: Client;
    'hero-slides': HeroSlide;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'use-cases': UseCasesSelect<false> | UseCasesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'trust-logos': TrustLogosSelect<false> | TrustLogosSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'pl' | 'de') | ('en' | 'pl' | 'de')[];
  globals: {
    useCasesSection: UseCasesSection;
  };
  globalsSelect: {
    useCasesSection: UseCasesSectionSelect<false> | UseCasesSectionSelect<true>;
  };
  locale: 'en' | 'pl' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility / SEO.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * URL path, e.g. "zabka".
   */
  slug: string;
  /**
   * e.g. "Cloud Development".
   */
  category?: string | null;
  /**
   * Client / company name.
   */
  client?: string | null;
  /**
   * Short summary shown on cards, and the caption set above the headline in the home page Cases band.
   */
  excerpt?: string | null;
  /**
   * Client logo (shown on the card).
   */
  logo?: (number | null) | Media;
  /**
   * Lead image for the case page, and the picture used by the home page Cases band. The band crops it to 4:5, 4:3 and 3:4 by position, so keep the subject centred.
   */
  heroImage?: (number | null) | Media;
  /**
   * Optional Tailwind gradient classes used when there is no image, e.g. "bg-gradient-to-br from-blue-600 via-blue-500 to-cyan-400".
   */
  gradient?: string | null;
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  results?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  stats?:
    | {
        value: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Show this case in the Cases band on the home page. The band takes the first three in Order and needs a Hero image on each; Excerpt is the caption above the headline. When nothing is ticked the band falls back to the three cases built into the site copy.
   */
  showOnHome?: boolean | null;
  /**
   * Marks this case as a lead entry for listings. It does NOT put the case on the home page: that is Show on home page.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first, in listings and in the home page Cases band.
   */
  order?: number | null;
  publishedAt?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  title: string;
  /**
   * URL path, e.g. "ai-transforming-business".
   */
  slug: string;
  /**
   * Short summary shown in listings. It is also the standfirst in the home page Insights band and the caption in the home page Stories band.
   */
  excerpt?: string | null;
  category?: ('ai' | 'development' | 'business' | 'technology' | 'cloud' | 'mobile') | null;
  /**
   * Cover art. Both home page bands need it: the Insights band shows it 16:9 beside the text, the Stories band shows it 16:9 above the headline. An insight without one is skipped by both.
   */
  coverImage?: (number | null) | Media;
  /**
   * Optional Tailwind gradient classes used when there is no image, e.g. "bg-gradient-to-br from-purple-600 via-violet-500 to-indigo-400".
   */
  gradient?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: string | null;
  /**
   * Estimated read time (minutes).
   */
  readTime?: number | null;
  publishedAt?: string | null;
  /**
   * Highlight as the lead article on the Insights page. It does NOT put the article on the home page: those are the two band checkboxes below.
   */
  featured?: boolean | null;
  /**
   * Show in the Insights band near the top of the home page, the tab strip that advances by itself. It takes the first five in Home order and each one needs a Home tag and a cover image. When nothing is ticked the band falls back to the five items built into the site copy.
   */
  showInInsightsBand?: boolean | null;
  /**
   * Show in the Stories band lower down the home page, the three staggered cards under Cases. It takes the first three in Home order and each one needs a cover image. When nothing is ticked the band falls back to the three stories built into the site copy.
   */
  showInStoriesBand?: boolean | null;
  /**
   * The short label on the tab strip of the home page Insights band, e.g. "Retail" or "EU AI Act". One or two words: the tags sit on a single row. Required by that band and unused by the Stories band.
   */
  homeTag?: string | null;
  /**
   * Position in whichever home page band this article is ticked for. Lower numbers show first.
   */
  homeOrder?: number | null;
  /**
   * Where the home page bands send a reader, when it should not be this article. Leave empty for the article itself. Use a path without a language prefix ("/services/forward-deployed-engineers") or a full address for somewhere else entirely ("https://quanty.ai"), which opens in a new tab.
   */
  homeHref?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The top banner. The most recently updated active announcement is shown. An announcement with a slug also gets its own page at "/announcements/<slug>".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  /**
   * Internal label (not shown on the site).
   */
  title: string;
  /**
   * Banner message.
   */
  text: string;
  /**
   * Optional call-to-action label.
   */
  linkText?: string | null;
  /**
   * Optional link, e.g. "/contact".
   */
  linkUrl?: string | null;
  /**
   * Heading of the announcement's own page. Falls back to the banner message.
   */
  pageTitle?: string | null;
  /**
   * Full content of the announcement page at "/announcements/<slug>".
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URL of the announcement page, e.g. "free-ai-consultations-for-startups". Leave empty for banner-only announcements.
   */
  slug?: string | null;
  publishedAt?: string | null;
  /**
   * Only active announcements can be shown.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * e.g. "Product Manager".
   */
  role?: string | null;
  photo?: (number | null) | Media;
  bio?: string | null;
  email?: string | null;
  /**
   * Full phone number, e.g. "+48 61 847-31-79".
   */
  phone?: string | null;
  /**
   * Full LinkedIn profile URL.
   */
  linkedin?: string | null;
  /**
   * Show this person in the homepage hero card. The first featured member is used.
   */
  featuredOnHome?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  /**
   * Headline, e.g. "Jak polskie firmy wdrażają AI?".
   */
  title: string;
  /**
   * Small accent label above the headline.
   */
  eyebrow?: string | null;
  /**
   * One or two supporting sentences.
   */
  description?: string | null;
  /**
   * Large visual shown next to the copy.
   */
  image?: (number | null) | Media;
  /**
   * Button label. Defaults to "Learn more".
   */
  ctaLabel?: string | null;
  /**
   * Where the button leads: an internal path (e.g. "/insights/ai-report") or a full URL.
   */
  href?: string | null;
  /**
   * Show this report on the landing page.
   */
  featured?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases".
 */
export interface UseCase {
  id: number;
  title: string;
  /**
   * Small label above the title, e.g. "Document AI".
   */
  category?: string | null;
  /**
   * Card background image.
   */
  image?: (number | null) | Media;
  /**
   * Drawing used when no image is uploaded. Left empty, the card falls back to the drawing that matches its position in the mosaic.
   */
  art?: ('document' | 'assistant' | 'forecast' | 'vision' | 'knowledge') | null;
  /**
   * Where the card leads: an internal path (e.g. "/insights/some-article") or a full URL.
   */
  href?: string | null;
  /**
   * Featured card renders as the large tile in the mosaic.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Workshop / engagement booking requests and contact submissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  /**
   * Which page the request came from.
   */
  offering:
    | 'ai-opportunity-workshop'
    | 'ai-discovery-sprint'
    | 'genai-proof-of-concept'
    | 'fractional-ai-team'
    | 'general';
  /**
   * How they found us.
   */
  hearAbout: 'search' | 'recommendation' | 'social' | 'event' | 'content' | 'other';
  message: string;
  consentTerms: boolean;
  consentMarketing?: boolean | null;
  /**
   * Site language at submission.
   */
  locale?: string | null;
  /**
   * Page path the form was on.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client logos for the hero's "Trusted by" strip. Active logos show in Order; when none are active the strip falls back to the dictionary text names.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-logos".
 */
export interface TrustLogo {
  id: number;
  /**
   * Client name — also the logo's alt text.
   */
  name: string;
  /**
   * Logo file — ideally SVG or PNG with a transparent background. It is recolored to white on the dark hero, so any logo color works.
   */
  logo: number | Media;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The "Selected clients" band on the home page. Active clients show in Order; when none are active the band falls back to the three names built into the site copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  /**
   * Company name, set in the large type of the home page band. Not translated: a company is called the same thing in every language.
   */
  name: string;
  /**
   * The single grey line under the name on the home page, e.g. "Autonomous store architecture". One short phrase, no full stop.
   */
  what: string;
  /**
   * Lower numbers show first. The band sets three across a row.
   */
  order?: number | null;
  /**
   * Uncheck to drop this client from the home page band without deleting the record.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The full screen slides at the top of the home page. One is chosen at random on load and the rest follow as each clip ends. Active slides play in Order; when none are active the hero falls back to the slides built into the site copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  /**
   * A short identity for this slide, e.g. "pluscode" or "logistics". Not shown to anyone: it is how the seed script finds this row again and how the page tells one slide from another. Lower case, no spaces.
   */
  key: string;
  /**
   * The one large line, set in white over the footage. A noun phrase, no full stop. Write it for this clip: the slide exists so the words and the picture say the same thing.
   */
  headline: string;
  /**
   * The single grey line under the headline. One short sentence.
   */
  subline: string;
  /**
   * Path to the H.264 file in public/hero/, e.g. /hero/logistics.mp4. This is the source the page offers first, because every browser and every phone can decode it. It must be encoded with faststart or it will not begin playing until the whole file has arrived.
   */
  mp4Path: string;
  /**
   * Optional path to a VP9 file in public/hero/. Offered second, for a browser built with no H.264 decoder. Leave empty and the slide plays the mp4 everywhere.
   */
  webmPath?: string | null;
  /**
   * Path to the still in public/hero/. It is what a visitor on a slow connection sees, and what stands in when a phone refuses to autoplay, so use the clip's own first frame: then the still and the first frame of playback are the same picture and nothing jumps.
   */
  posterPath: string;
  /**
   * Optional. Upload a still here to use instead of the path above, when the poster needs changing and a deploy does not. The clips themselves cannot be uploaded: they ship with the site so the first screen survives a fresh deploy.
   */
  posterOverride?: (number | null) | Media;
  /**
   * How much ink is washed over the TOP edge of this clip, 0 to 1. It is what keeps the header legible over bright footage. Measured, not chosen: read the average luma of the top strip of the clip and raise this until white type on it is comfortable. A dark clip needs less.
   */
  overlayTop?: number | null;
  /**
   * The same wash at the BOTTOM edge, where the headline sits. Raise it for pale footage, lower it for footage shot at night, and check the result rather than trusting the number.
   */
  overlayBottom?: number | null;
  /**
   * Lower numbers play first. The playlist starts on a random slide and then follows this order.
   */
  order?: number | null;
  /**
   * Uncheck to take this slide out of the playlist without deleting it. With every slide unchecked the hero falls back to the site copy.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'use-cases';
        value: number | UseCase;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'trust-logos';
        value: number | TrustLogo;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  client?: T;
  excerpt?: T;
  logo?: T;
  heroImage?: T;
  gradient?: T;
  overview?: T;
  challenge?: T;
  solution?: T;
  results?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  showOnHome?: T;
  featured?: T;
  order?: T;
  publishedAt?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  coverImage?: T;
  gradient?: T;
  content?: T;
  author?: T;
  readTime?: T;
  publishedAt?: T;
  featured?: T;
  showInInsightsBand?: T;
  showInStoriesBand?: T;
  homeTag?: T;
  homeOrder?: T;
  homeHref?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  linkText?: T;
  linkUrl?: T;
  pageTitle?: T;
  body?: T;
  slug?: T;
  publishedAt?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  email?: T;
  phone?: T;
  linkedin?: T;
  featuredOnHome?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  title?: T;
  eyebrow?: T;
  description?: T;
  image?: T;
  ctaLabel?: T;
  href?: T;
  featured?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases_select".
 */
export interface UseCasesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  image?: T;
  art?: T;
  href?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  offering?: T;
  hearAbout?: T;
  message?: T;
  consentTerms?: T;
  consentMarketing?: T;
  locale?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-logos_select".
 */
export interface TrustLogosSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  what?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  key?: T;
  headline?: T;
  subline?: T;
  mp4Path?: T;
  webmPath?: T;
  posterPath?: T;
  posterOverride?: T;
  overlayTop?: T;
  overlayBottom?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "useCasesSection".
 */
export interface UseCasesSection {
  id: number;
  /**
   * Small eyebrow above the title, e.g. "Zastosowane AI, na produkcji".
   */
  label?: string | null;
  /**
   * Section heading, e.g. "Ambicja w działaniu".
   */
  title?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "useCasesSection_select".
 */
export interface UseCasesSectionSelect<T extends boolean = true> {
  label?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}