import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { nohemi } from './fonts';
import { AnnouncementProvider } from "@/components/AnnouncementContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();

  return (
    <html lang="en">
      <body
        className={`${nohemi.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <AnnouncementProvider>
            {children}
          </AnnouncementProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
